sonar.host.url=http://localhost:9000 
sonar.projectKey=frontend
sonar.token=sqp_76dead56c6f50c9bec55a60483629930985fd2bb
sonar.sources=src
sonar.javascript.node.maxspace=4096

# Exclude unnecessary directories and files
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.test.js,**/*.spec.js

# Limit analysis to JavaScript and TypeScript files
sonar.inclusions=**/*.js,**/*.ts

# Use pre-generated lcov reports for TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info