sonar.host.url=http://localhost:9000 
sonar.projectKey=backend
sonar.token=sqp_51c216b8f388e0638cd08a5f109dbf9c1c95c9f3
sonar.sources=.
sonar.javascript.node.maxspace=2048

# Exclude unnecessary directories and files
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.test.js,**/*.spec.js,models/*.js,

# Limit analysis to JavaScript and TypeScript files
sonar.inclusions=**/*.js,**/*.ts

# Use pre-generated lcov reports for TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info
