apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    env:
    - name: JENKINS_URL
      value: "http://localhost:8080/"
    - name: JENKINS_SECRET
      value: "********"
    - name: JENKINS_AGENT_NAME
      value: "jenkins-agent"
    - name: JENKINS_NAME
      value: "jenkins-agent"
    - name: JENKINS_AGENT_WORKDIR
      value: "/home/jenkins/agent"
    volumeMounts:
    - name: workspace-volume
      mountPath: "/home/jenkins/agent"
    - name: docker-socket
      mountPath: /var/run/docker.sock
  - name: docker
    image: docker:latest
    command:
    - "dockerd-entrypoint.sh"
    args:
    - "--host=tcp://0.0.0.0:2375"
    - "--host=unix:///var/run/docker.sock"
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: workspace-volume
    emptyDir: {}
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
