# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: muschan/gathering-backend:latest # Byt ut till ditt Docker Hub repository
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/gatheringdb" # Anslutning till MongoDB service