apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: development
spec:
  type: LoadBalancer # or NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
      # if spec is NodePort then "nodePort: 30000"
      
