name: Notify Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

      - name: Get author name
        id: author_name
        run: echo "AUTHOR_NAME=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV

      - name: Get changes
        id: changes
        run: |
          git diff --name-only ${{ github.sha }}^ ${{ github.sha }} > changed_files.txt
          if [ -s changed_files.txt ]; then
            echo "CHANGES=$(cat changed_files.txt)" >> $GITHUB_ENV
          else
            echo "CHANGES=No changes detected" >> $GITHUB_ENV
          fi

      - name: Set event context
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          else
            echo "PR_URL=" >> $GITHUB_ENV
          fi

      - name: Generate URLs to changes
        if: ${{ steps.changes.outputs.CHANGES != 'No changes detected' }}
        id: generate_urls
        run: |
          URL_PREFIX="https://github.com/${{ github.repository }}/commit/${{ github.sha }}/files#diff-"
          CHANGES_URLS=""
          while IFS= read -r file; do
            CHANGES_URLS+="\n[${file}](${URL_PREFIX}${file})"
          done < changed_files.txt
          echo "CHANGES_URLS=$CHANGES_URLS" >> $GITHUB_ENV

      - name: Notify Discord on success
        if: success()
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            **Build Status**: SUCCESS
            **Commit Message**: ${{ env.COMMIT_MESSAGE }}
            **Author**: ${{ env.AUTHOR_NAME }}
            **Changes**:${{ env.CHANGES }}
            ${{ env.PR_URL && format('\n**Pull Request URL**: {0}', env.PR_URL) }}
            ${{ env.CHANGES_URLS }}

      - name: Notify Discord on failure
        if: failure()
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            **Build Status**: FAILURE
            **Commit Message**: ${{ env.COMMIT_MESSAGE }}
            **Author**: ${{ env.AUTHOR_NAME }}
            **Changes**:${{ env.CHANGES }}
            ${{ env.PR_URL && format('\n**Pull Request URL**: {0}', env.PR_URL) }}
            ${{ env.CHANGES_URLS }}
